-- TYL-66: freeze Gmail drafts when the owner queues a send for the assistant.
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "queuedTo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "queuedSubject" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "queuedBody" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "queuedAt" TIMESTAMP(3);
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "gmailMessageId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "gmailThreadId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "sendFailedReason" TEXT NOT NULL DEFAULT '';
