ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "approvedText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "approvedPersonName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "approvedCompanyName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMP(3);
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "externalMessageId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "failedReason" TEXT NOT NULL DEFAULT '';
