ALTER TABLE "LeadDraft" ADD COLUMN IF NOT EXISTS "fromAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeadDraft" ALTER COLUMN "leadId" DROP NOT NULL;
ALTER TABLE "LeadEvent" ALTER COLUMN "leadId" DROP NOT NULL;
